docs: updated change log for levski release
edgexfoundry/device-usb-camera pull request #118
Opened 2022-12-08 17:20 UTC by brianointel

Signed-off-by: brianointel <brian.j.osburn@intel.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-12-09 22:00 UTC, bill-mahoney submitted a review, later dismissed
LGTM

2022-12-12 17:34 UTC, presatish approved these changes, later dismissed
LGTM

2022-12-12 19:29 UTC, ChristianDarr-personal requested changes

2022-12-12 19:29 UTC, ChristianDarr-personal commented on CHANGELOG.md
> +- startStreaming now returns all errors ([#50aed43](https://github.com/edgexfoundry/device-usb-camera/commits/50aed43))
```suggestion
- error forwarding on startStreaming command ([#113] https://github.com/edgexfoundry/device-usb-camera/issues/113) ([#02bc335] (https://github.com/edgexfoundry/device-usb-camera/commit/02bc3351eb583ffe88737b5638435757cc287900)
```

2022-12-12 19:29 UTC, ChristianDarr-personal commented on CHANGELOG.md
> +- startStreaming now returns all errors ([#50aed43](https://github.com/edgexfoundry/device-usb-camera/commits/50aed43))
So I just noticed this, but it looks like my fix for issue #23 did not get squashed and merged, so all 3 of my commits are sitting in the repo and are not attributed to one single pr (#113). Is this an issue?

2022-12-12 21:46 UTC, presatish commented on CHANGELOG.md
> +- startStreaming now returns all errors ([#50aed43](https://github.com/edgexfoundry/device-usb-camera/commits/50aed43))
I think whatever you have suggested is good, not seeing any issue.

2022-12-14 16:32 UTC, ChristianDarr-personal approved these changes

2022-12-14 16:54 UTC, lenny-intel commented
recheck

2022-12-14 17:51 UTC, merged