fix: Rename EnableRtspServer to DisableRtspServer
edgexfoundry/device-usb-camera pull request #270
Opened 2023-08-22 22:16 UTC by marcpfuller

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) n/a
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)  tbd
  <link to docs PR>

## Testing Instructions
1. run `make test`
2. verify all tests pass
3. start up edgex via edgex-compose with no-secty: `make run no-secty`
4. run device-usb-camera with `disableRtspServer` set to false `./device-usb-camera -cp -d -o`
5. verify RTSP server starts
6. run device-usb-camera with `disableRtspServer` set to true `./device-usb-camera -cp -d -o`
7. verify RTSP server does not start

## New Dependency Instructions (If applicable)

2023-08-22 22:17 UTC, marcpfuller commented
This PR addresses comments made after merge for #268

2023-08-22 22:25 UTC, lenny-intel submitted a review, later dismissed
LGTM

2023-08-23 08:42 UTC, farshidtz approved these changes, later dismissed
Looks good.

Note that the snap tests are still failing because the RTCP binary path has been hardcoded. See https://github.com/edgexfoundry/device-usb-camera/pull/268#discussion_r1302646697

2023-08-23 20:40 UTC, lenny-intel submitted a review, later dismissed

2023-08-23 20:40 UTC, lenny-intel commented on internal/driver/driver.go
> +	rtspExecutable := d.ds.DriverConfigs()[RtspServerExe]
Should handle not set in a better way, like check for empty and return error that it isn't set

2023-08-23 23:15 UTC, marcpfuller commented
@farshidtz  I have made the file path to rtsp server  a configurable. Snap no longer needs to start rtsp server, and you will need to do a environment variable override for the snap location of rtsp simple server. The environment variable override would be `DRIVER_RTSPSERVEREXECUTABLE`

2023-08-24 00:36 UTC, presatish commented on internal/driver/driver.go
> +	// if DisableRtspServer config id blank disableRtspServer should be false
```suggestion
	// if DisableRtspServer config parameter is empty then it should be set to false
```

2023-08-24 00:36 UTC, presatish commented on internal/driver/driver.go
> +			return fmt.Errorf("failed to parse EnableRtspServer config: %s", err.Error())
```suggestion
			return fmt.Errorf("failed to parse DisableRtspServer config: %s", err.Error())
```

2023-08-25 22:01 UTC, ajcasagrande requested changes
Unfortunately there are still some issues regarding the architectural design behind this story.

When `DisableRtspServer` is set to true, then all REST APIs related to streaming will return errors (as designed). However, this does not account for the case where the user wants to disable the internal rtsp server because they want to run it separately (via docker, snap, on a different machine, etc).

In those cases, the user would (optionally) set the `RtspServerHostName` to something different, and disable the internal rtsp server.  I am not sure the best way to handle re-enabling the REST APIs.

Some options:
- Add another config var to specify that an external one is in use
- Change `DisableRtspServer` to be an enum `RtspServerMode` with:
  - `internal` (or `enabled`) - run server and enable apis
  - `external` - do not run server, but enable apis
  - `disabled` - do not run server and disable apis

Open to recommendations @farshidtz @lenny-intel

2023-08-25 22:01 UTC, ajcasagrande commented on internal/driver/driver.go
> +	if len(disableRtspServer) == 0 {
```suggestion
	if disableRtspServer == "" {
```

2023-08-25 22:01 UTC, ajcasagrande commented on internal/driver/driver.go
> +	// if DisableRtspServer config parameter is empty then it should be set to false
```suggestion
	// If DisableRtspServer config parameter is empty, then it should be
	// set to false to retain backwards compatibility
```

2023-08-25 22:01 UTC, ajcasagrande commented on internal/driver/driver.go
> +	if len(rtspExecutable) == 0 {
```suggestion
	if rtspExecutable == "" {
```

2023-08-27 10:21 UTC, farshidtz commented
> Unfortunately there are still some issues regarding the architectural design behind this story.
> 
> When `DisableRtspServer` is set to true, then all REST APIs related to streaming will return errors (as designed). However, this does not account for the case where the user wants to disable the internal rtsp server because they want to run it separately (via docker, snap, on a different machine, etc).
> 
> In those cases, the user would (optionally) set the `RtspServerHostName` to something different, and disable the internal rtsp server. I am not sure the best way to handle re-enabling the REST APIs.
> 
> Some options:
> 
> * Add another config var to specify that an external one is in use
> * Change `DisableRtspServer` to be an enum `RtspServerMode` with:
>   
>   * `internal` (or `enabled`) - run server and enable apis
>   * `external` - do not run server, but enable apis
>   * `disabled` - do not run server and disable apis
> 
> Open to recommendations @farshidtz @lenny-intel

Is there a use case where users would use this device service without RTSP server and the streaming APIs? 
If not, then the enum could be `RtspServer: internal|external`.

2023-08-28 15:07 UTC, lenny-goodell commented
> Some options:
> 
> * Add another config var to specify that an external one is in use
> * Change `DisableRtspServer` to be an enum `RtspServerMode` with:
>   
>   * `internal` (or `enabled`) - run server and enable apis
>   * `external` - do not run server, but enable apis
>   * `disabled` - do not run server and disable apis

I like RtspServerMode with values:

- `internal` - run server and enable apis
- `external` - do not run server, but enable apis
- `none` - do not run server and disable apis
- `` - Defaults to `internal` 

> Is there a use case where users would use this device service without RTSP server and the streaming APIs?
@farshidtz , yes when only need control features and/or accessing the /dev device directly.

2023-08-29 21:23 UTC, ajcasagrande commented
> I like RtspServerMode with values:
> 
> * `internal` - run server and enable apis
> * `external` - do not run server, but enable apis
> * `none` - do not run server and disable apis
> * `` - Defaults to `internal`

I like this approach, and if the user specifies anything out of this range, we can error out as bad configuration

2023-09-01 16:39 UTC, ajcasagrande commented
Ready for review again

2023-09-01 18:11 UTC, seanohair22 approved these changes
LGTM! Tested and works with valid values and catches bad config values!

2023-09-01 22:47 UTC, presatish approved these changes
LGTM

2023-09-06 20:37 UTC, ajcasagrande approved these changes

2023-09-06 20:38 UTC, merged