feat: update example device files
edgexfoundry/device-usb-camera pull request #273
Opened 2023-08-25 01:31 UTC by ChristianDarr-personal

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) N/A
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) N/A
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2023-08-25 22:10 UTC, ajcasagrande commented on cmd/res/devices/intel.realsense.yaml.example
> +        Paths: ["/dev/video0","/dev/video2","/dev/video4",]
Would it be better to split these out using the `-` syntax?

```suggestion
        Paths:
         - "/dev/video0"
         - "/dev/video2"
         - "/dev/video4"
```

2023-08-25 22:10 UTC, ajcasagrande commented on cmd/res/devices/general.usb.camera.yaml.example
> +        Paths: ["/dev/video0",]
Is the `,]` ending necessary to make Yaml turn it into an array?

2023-08-25 22:57 UTC, ajcasagrande approved these changes

2023-08-27 23:56 UTC, presatish approved these changes
LGTM

2023-08-29 20:07 UTC, presatish requested changes
When I tested using the document (used Paths) it was leading to some issues. So this needs to be tested. Also the doc needs change too.

2023-08-31 00:02 UTC, presatish approved these changes
LGTM

2023-08-31 00:03 UTC, merged